### ISSUE TITLE
basic content-negotation for error message

### ISSUE THREAD

**Issue by jeanlaurent** [CodeStory/fluent-http#117]
We could implement a basic [content negotiation](http://en.wikipedia.org/wiki/Content_negotiation) routine to answer the error message in the content accepted by the request. 

if the request accept `application/json` return `application/json` error messages. Default to `text/html`

**Comment by code-story** [comment]
+1

**Comment by jeantil** [comment]
Thanks this would be great.

If full blown content negotiation is too much to implement right away. You could improve consistency in the returned types :
for Payload, Model, ModelAndView, keep the current behaviour
for types which are automatically converted to json through the jackson mapper, return json 404 instead of a text/html with a base 64 encoded image (this makes it painful to drive the api through the command line)
